package com.fossm.userservice.model.enums;

public enum ReportReason {

  HARASSMENT_OR_BULLYING,
  HATE_SPEECH_OR_DISCRIMINATION_OR_FAKE_NEWS,
  SEXUAL_CONTENT,
  VIOLENCE_AND_ABUSE,
  CHILD_EXPLOITATION,
  IMPERSONATION_OR_INFRINGEMENT,
  SPAM

}
